/* Auto-generated by genmsg_cpp for file /home/tom/ros/graphslam/msg/pose_laser.msg */
#ifndef GRAPHSLAM_MESSAGE_POSE_LASER_H
#define GRAPHSLAM_MESSAGE_POSE_LASER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"
#include "sensor_msgs/LaserScan.h"

namespace graphslam
{
template <class ContainerAllocator>
struct pose_laser_ {
  typedef pose_laser_<ContainerAllocator> Type;

  pose_laser_()
  : pose()
  , scan()
  {
  }

  pose_laser_(const ContainerAllocator& _alloc)
  : pose(_alloc)
  , scan(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  pose;

  typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan_type;
   ::sensor_msgs::LaserScan_<ContainerAllocator>  scan;


  typedef boost::shared_ptr< ::graphslam::pose_laser_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graphslam::pose_laser_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pose_laser
typedef  ::graphslam::pose_laser_<std::allocator<void> > pose_laser;

typedef boost::shared_ptr< ::graphslam::pose_laser> pose_laserPtr;
typedef boost::shared_ptr< ::graphslam::pose_laser const> pose_laserConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::graphslam::pose_laser_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::graphslam::pose_laser_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace graphslam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::graphslam::pose_laser_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::graphslam::pose_laser_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::graphslam::pose_laser_<ContainerAllocator> > {
  static const char* value() 
  {
    return "da9754961fde500c1e9f0c89a9e1e879";
  }

  static const char* value(const  ::graphslam::pose_laser_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xda9754961fde500cULL;
  static const uint64_t static_value2 = 0x1e9f0c89a9e1e879ULL;
};

template<class ContainerAllocator>
struct DataType< ::graphslam::pose_laser_<ContainerAllocator> > {
  static const char* value() 
  {
    return "graphslam/pose_laser";
  }

  static const char* value(const  ::graphslam::pose_laser_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::graphslam::pose_laser_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PoseStamped pose\n\
sensor_msgs/LaserScan scan\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: sensor_msgs/LaserScan\n\
# Single scan from a planar laser range-finder\n\
#\n\
# If you have another ranging device with different behavior (e.g. a sonar\n\
# array), please find or create a different message, since applications\n\
# will make fairly laser-specific assumptions about this data\n\
\n\
Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
                         \n\
float32 angle_min        # start angle of the scan [rad]\n\
float32 angle_max        # end angle of the scan [rad]\n\
float32 angle_increment  # angular distance between measurements [rad]\n\
\n\
float32 time_increment   # time between measurements [seconds] - if your scanner\n\
                         # is moving, this will be used in interpolating position\n\
                         # of 3d points\n\
float32 scan_time        # time between scans [seconds]\n\
\n\
float32 range_min        # minimum range value [m]\n\
float32 range_max        # maximum range value [m]\n\
\n\
float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n\
float32[] intensities    # intensity data [device-specific units].  If your\n\
                         # device does not provide intensities, please leave\n\
                         # the array empty.\n\
\n\
";
  }

  static const char* value(const  ::graphslam::pose_laser_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::graphslam::pose_laser_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pose);
    stream.next(m.scan);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pose_laser_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graphslam::pose_laser_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::graphslam::pose_laser_<ContainerAllocator> & v) 
  {
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "scan: ";
s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GRAPHSLAM_MESSAGE_POSE_LASER_H

